CREATE TABLE IF NOT EXISTS usuarios (
 Id INT PRIMARY KEY AUTO_INCREMENT, Nome VARCHAR(100) NOT NULL,
 Email VARCHAR(180) NOT NULL UNIQUE, SenhaHash VARCHAR(500) NOT NULL, Perfil VARCHAR(30) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS filhas (
 Id INT PRIMARY KEY AUTO_INCREMENT, Nome VARCHAR(80) NOT NULL, Escolaridade VARCHAR(100) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS semestres (
 Id INT PRIMARY KEY AUTO_INCREMENT, Ano INT NOT NULL, Numero INT NOT NULL,
 UNIQUE KEY uq_periodo (Ano, Numero), CHECK (Numero IN (1,2))
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS disciplinas (
 Id INT PRIMARY KEY AUTO_INCREMENT, Nome VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS boletins (
 Id INT PRIMARY KEY AUTO_INCREMENT, FilhaId INT NOT NULL, SemestreId INT NOT NULL,
 FOREIGN KEY (FilhaId) REFERENCES filhas(Id), FOREIGN KEY (SemestreId) REFERENCES semestres(Id),
 UNIQUE KEY uq_boletim (FilhaId, SemestreId)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notas (
 BoletimId INT NOT NULL, DisciplinaId INT NOT NULL, Valor DECIMAL(4,2) NOT NULL,
 PRIMARY KEY (BoletimId, DisciplinaId), FOREIGN KEY (BoletimId) REFERENCES boletins(Id),
 FOREIGN KEY (DisciplinaId) REFERENCES disciplinas(Id), CHECK (Valor BETWEEN 0 AND 10)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS regras_recompensa (
 Id INT PRIMARY KEY AUTO_INCREMENT, MediaMinima DECIMAL(4,2) NOT NULL UNIQUE,
 Valor DECIMAL(10,2) NOT NULL, CHECK (MediaMinima BETWEEN 0 AND 10), CHECK (Valor >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS recompensas (
 Id INT PRIMARY KEY AUTO_INCREMENT, BoletimId INT NOT NULL UNIQUE,
 Valor DECIMAL(10,2) NOT NULL, FOREIGN KEY (BoletimId) REFERENCES boletins(Id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS pagamentos (
 Id INT PRIMARY KEY AUTO_INCREMENT, RecompensaId INT NOT NULL UNIQUE, UsuarioId INT NOT NULL,
 DataPagamento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (RecompensaId) REFERENCES recompensas(Id), FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id)
) ENGINE=InnoDB;
